//------------------------------------------------------------------------
// Copyright(c) 2024 Litleleprikon VST.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"LitleleprikonDelay.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"LitleleprikonDelay VST3 (64Bit)"
#else
#define stringFileDescription	"LitleleprikonDelay VST3"
#endif
#define stringCompanyName		"Litleleprikon VST\0"
#define stringLegalCopyright	"Copyright(c) 2024 Litleleprikon VST."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
